server:
  port: 2333

lavalink:
  plugins:
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.3"
      repository: "https://maven.lavalink.dev/releases"

  server:
    password: "youshallnotpass"
    sources:
      youtube: false
      bandcamp: false
      soundcloud: false
      twitch: false
      vimeo: false
      http: false
      local: false

plugins:
  lavasrc:
    providers:
      - "spsearch:%QUERY%"
    sources:
      spotify: true
    spotify:
      clientId: "1d05f4f043904d099cd20652873f86ff"
      clientSecret: "c33980434eaf4e7ab3def3ff2a9950e1"
